# This file is formatted using TOML. https://github.com/toml-lang/toml
#
# To add new scan use [NAME_OF_SCAN], this will not be used but will instead just allow us to separate scans in this file.
# Please do not use special characters here, other than underscores.
#

# Each scan config should have the following sections:
# name, enabled, rrules.freq, rrules.interval, rrules.byday,text_targets

# _"enabled" config_
# enabled will enable or disable your scheduled scan with a boolean
#
# _"rrules" config_
# rrules are rules that will configure when your scans will run.
# "freq" = "ON_DEMAND, DAILY, WEEKLY, MONTHLY, YEARLY"
# "interval" = "1, 2, 3 or x being every x number of days, weeks etc"
# "byday" = "MO, TU, WE, TH, FR"

# _"text_targets" config_
# text targets is a comma seperated list of targets, these can be URLs or IP addresses
# "text_targets" = "www.gov.uk, 216.58.198.174"

# _"starttime" config_
# "startime" refers to the date and time the first scan will run and must be in "YYYYMMDDTHHMMSS" format

[gov_uk_weekly]
"name" = "govuk weekly scan"
"enabled" = 1
"rrules.freq" = "WEEKLY"
"rrules.interval" = "3"
"rrules.byday" = "MO"
"starttime" = "20200501T100000" 
"text_targets" = "www.gov.uk"

[notify]
"name" = "notify weekly scan"
"enabled" = 1
"rrules.freq" = "WEEKLY"
"rrules.interval" = "2"
"rrules.byday" = "TU"
"starttime" = "20200602T100000"
"text_targets" = "www.notifications.service.gov.uk"

[misc_paas]
"name" = "miscellaneous paas weekly scan"
"enabled" = 1
"rrules.freq" = "WEEKLY"
"rrules.interval" = "2"
"rrules.byday" = "WE"
"starttime" = "20200603T100000"
"text_targets" = "admin.cloud.service.gov.uk, cloud.service.gov.uk, cybertools.cloudapps.digital, gds-way.cloudapps.digital"

[reg_to_vote]
"name" = "register to vote weekly scan"
"enabled" = 1
"rrules.freq" = "WEEKLY"
"rrules.interval" = "2"
"rrules.byday" = "TH"
"starttime" = "20200528T133000"
"text_targets" = "www.registertovote.service.gov.uk"

[verify]
"name" = "verify external weekly scan"
"enabled" = 1
"rrules.freq" = "WEEKLY"
"rrules.interval" = "2"
"rrules.byday" = "FR"
"starttime" = "20200529T150000"
"text_targets" = "www.signin.service.gov.uk, www.verify.service.gov.uk"

[govuk_pay]
"name" = "pay external weekly scan"
"enabled" = 1
"rrules.freq" = "WEEKLY"
"rrules.interval" = "2"
"rrules.byday" = "TH"
"starttime" = "20200604T100000"
"text_targets" = "www.payments.service.gov.uk, selfservice.payments.service.gov.uk"

[external_network]
"name" = "external weekly scan"
"enabled" = 1
"rrules.freq" = "WEEKLY"
"rrules.interval" = "2"
"rrules.byday" = "FR"
"starttime" = "20200605T100000"
"text_targets" = "213.86.153.212, 213.86.153.213, 213.86.153.214, 213.86.153.235, 213.86.153.236, 213.86.153.237, 85.133.67.244"