health_status_notify: &health_status_notify
  put: health-notification


resource_types:
  - name: http-api
    type: docker-image
    source:
      repository: gdscyber/http-api-resource

resources:
  - name: cyber-security-nessus-git
    icon: github-circle
    type: git
    source:
      uri: https://github.com/alphagov/cyber-security-nessus.git
      branch: master

  - name: toml-nessus-git
    icon: github-circle
    type: git
    source:
      uri: https://github.com/alphagov/cyber-security-nessus.git
      branch: master
      paths:
        - scan_config/scan.toml

  - name: health-notification
    type: http-api
    source:
      uri: https://((health_host_prod))/?alert_type=concourse$&alert_name=health
      method: POST
      headers:
        Authorization: "Bearer ((health_token_prod))"
      json:
        service: "{service}"
        state: "{health}"
        message: "{message}"
        pipeline: "{BUILD_PIPELINE_NAME}"
        job: "{BUILD_JOB_NAME}"
        build_number: "{BUILD_NAME}"
      service: "Nessus Pipeline"


jobs:
  - name: python_validation
    serial: false
    plan:
      - get: cyber-security-nessus-git
        trigger: true
      - task: run-lambda-validation
        config:
          inputs:
          - name: cyber-security-nessus-git
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: gdscyber/cyber-security-concourse-base-image
          run:
            path: bash
            args:
              - -c
              - |
                pip install pipenv
                cd cyber-security-nessus-git
                pipenv --python 3.7
                pipenv install --dev

                # These are needed to prevent the tests from contacting the AWS magic HTTP server.
                export AWS_ACCESS_KEY_ID=AKIA00AA00AAAA0A0AAA
                export AWS_SECRET_ACCESS_KEY=AAAAAAAAAAAAAAAAAAAAAAAAAAA
                export AWS_DEFAULT_REGION=${region:-eu-west-2}

                pipenv run pytest
        on_success:
          <<: *health_status_notify
          params:
            message: "Nessus python tests passed."
            health: healthy
        on_failure:
          <<: *health_status_notify
          params:
            message: "Nessus python tests failed"
            health: unhealthy

  - name: terraform_validation
    serial: false
    plan:
      - get: cyber-security-nessus-git
        trigger: true
      - task: run-terraform-fmt
        config:
          inputs:
          - name: cyber-security-nessus-git
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: gdscyber/cyber-security-concourse-base-image
          run:
            path: bash
            args:
              - -c
              - |
                cd cyber-security-nessus-git
                terraform fmt -diff -check -recursive
        on_success:
          <<: *health_status_notify
          params:
            message: "Nessus terraform validated."
            health: healthy
        on_failure:
          <<: *health_status_notify
          params:
            message: "Failed to validate nessus terraform."
            health: unhealthy

  - name: nessus_deploy
    serial: true
    plan:
      - get: cyber-security-nessus-git
        passed: [terraform_validation, python_validation]
        trigger: true
      - task: terraform_deploy
        config:
          inputs:
          - name: cyber-security-nessus-git
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: gdscyber/cyber-security-concourse-base-image
          run:
            path: /bin/bash
            args:
              - -c
              - |
                source /usr/local/bin/sts-assume-role.sh ((role_arn)) 'eu-west-2'

                pip install pipenv

                cd cyber-security-nessus-git

                pipenv --python 3.7
                pipenv install

                make

                cd terraform

                terraform init
                terraform apply --auto-approve
        on_success:
          <<: *health_status_notify
          params:
            message: "Nessus deployed successfully."
            health: healthy
        on_failure:
          <<: *health_status_notify
          params:
            message: "Failed to deploy nessus."
            health: unhealthy

  - name: generate_keys
    serial: true
    plan:
      - get: cyber-security-nessus-git
        passed: [nessus_deploy]
        trigger: true
      - task: generate_api_keys
        config:
          inputs:
          - name: cyber-security-nessus-git
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: gdscyber/cyber-security-concourse-base-image
          run:
            path: /bin/bash
            args:
              - -c
              - |
                pip install pipenv

                cd cyber-security-nessus-git
                pipenv --python 3.7
                pipenv install

                source /usr/local/bin/sts-assume-role.sh ((role_arn)) 'eu-west-2'
                cd terraform
                terraform init
                export fqdn=$(terraform output fqdn)
                cd ..
                pipenv run python generate_api_keys.py
        on_success:
          <<: *health_status_notify
          params:
            message: "API keys generated successfully."
            health: healthy
        on_failure:
          <<: *health_status_notify
          params:
            message: "Failed to generate nessus API keys."
            health: unhealthy

  - name: schedule_scans_update
    serial: false
    plan:
      - get: toml-nessus-git
        trigger: true
      - get: cyber-security-nessus-git
        passed: [generate_keys]
        trigger: true
      - task: update_scheduled_scans
        config:
          inputs:
          - name: toml-nessus-git
          - name: cyber-security-nessus-git
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: gdscyber/cyber-security-concourse-base-image
          run:
            path: bash
            args:
              - -c
              - |
                cp toml-nessus-git/scan_config/scan.toml cyber-security-nessus-git/scan_config/scan.toml

                cd cyber-security-nessus-git

                pip install pipenv
                pipenv --python 3.7
                pipenv install

                source /usr/local/bin/sts-assume-role.sh ((role_arn)) 'eu-west-2'
                pipenv run python schedule_scans.py
        on_success:
          <<: *health_status_notify
          params:
            message: "Nessus has scheduled new scans."
            health: healthy
        on_failure:
          <<: *health_status_notify
          params:
            message: "Failed to schedule new scans."
            health: unhealthy

  - name: Process Scans
    serial: false
    plan:
      - get: cyber-security-nessus-git
        passed: [schedule_scans_update]
        trigger: true
      - task: process_scans
        config:
          inputs:
          - name: cyber-security-nessus-git
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: gdscyber/cyber-security-concourse-base-image
          run:
            path: bash
            args:
              - -c
              - |
                source /usr/local/bin/sts-assume-role.sh ((role_arn)) 'eu-west-2'
                pip install pipenv
                cd cyber-security-nessus-git
                pipenv --python 3.7
                pipenv install --dev
                pipenv run python process_scans.py

        on_success:
          <<: *health_status_notify
          params:
            message: "Nessus processed scans."
            health: healthy
        on_failure:
          <<: *health_status_notify
          params:
            message: "Nessus FAILED to process scans"
            health: unhealthy
